/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutVisualizeImport } from './routes/_layout/visualize'
import { Route as LayoutClassifyImport } from './routes/_layout/classify'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutVisualizeRoute = LayoutVisualizeImport.update({
  id: '/visualize',
  path: '/visualize',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutClassifyRoute = LayoutClassifyImport.update({
  id: '/classify',
  path: '/classify',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/classify': {
      id: '/_layout/classify'
      path: '/classify'
      fullPath: '/classify'
      preLoaderRoute: typeof LayoutClassifyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/visualize': {
      id: '/_layout/visualize'
      path: '/visualize'
      fullPath: '/visualize'
      preLoaderRoute: typeof LayoutVisualizeImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutClassifyRoute: typeof LayoutClassifyRoute
  LayoutVisualizeRoute: typeof LayoutVisualizeRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutClassifyRoute: LayoutClassifyRoute,
  LayoutVisualizeRoute: LayoutVisualizeRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/classify': typeof LayoutClassifyRoute
  '/visualize': typeof LayoutVisualizeRoute
  '/': typeof LayoutIndexRoute
}

export interface FileRoutesByTo {
  '/classify': typeof LayoutClassifyRoute
  '/visualize': typeof LayoutVisualizeRoute
  '/': typeof LayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/classify': typeof LayoutClassifyRoute
  '/_layout/visualize': typeof LayoutVisualizeRoute
  '/_layout/': typeof LayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/classify' | '/visualize' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/classify' | '/visualize' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/classify'
    | '/_layout/visualize'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/classify",
        "/_layout/visualize",
        "/_layout/"
      ]
    },
    "/_layout/classify": {
      "filePath": "_layout/classify.tsx",
      "parent": "/_layout"
    },
    "/_layout/visualize": {
      "filePath": "_layout/visualize.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
