/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutClassifyImport } from './routes/_layout/classify'
import { Route as LayoutVisualizeRecordsImport } from './routes/_layout/visualize/records'
import { Route as LayoutVisualizeChartsImport } from './routes/_layout/visualize/charts'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutClassifyRoute = LayoutClassifyImport.update({
  id: '/classify',
  path: '/classify',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutVisualizeRecordsRoute = LayoutVisualizeRecordsImport.update({
  id: '/visualize/records',
  path: '/visualize/records',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutVisualizeChartsRoute = LayoutVisualizeChartsImport.update({
  id: '/visualize/charts',
  path: '/visualize/charts',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/classify': {
      id: '/_layout/classify'
      path: '/classify'
      fullPath: '/classify'
      preLoaderRoute: typeof LayoutClassifyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/visualize/charts': {
      id: '/_layout/visualize/charts'
      path: '/visualize/charts'
      fullPath: '/visualize/charts'
      preLoaderRoute: typeof LayoutVisualizeChartsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/visualize/records': {
      id: '/_layout/visualize/records'
      path: '/visualize/records'
      fullPath: '/visualize/records'
      preLoaderRoute: typeof LayoutVisualizeRecordsImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutClassifyRoute: typeof LayoutClassifyRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutVisualizeChartsRoute: typeof LayoutVisualizeChartsRoute
  LayoutVisualizeRecordsRoute: typeof LayoutVisualizeRecordsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutClassifyRoute: LayoutClassifyRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutVisualizeChartsRoute: LayoutVisualizeChartsRoute,
  LayoutVisualizeRecordsRoute: LayoutVisualizeRecordsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/classify': typeof LayoutClassifyRoute
  '/': typeof LayoutIndexRoute
  '/visualize/charts': typeof LayoutVisualizeChartsRoute
  '/visualize/records': typeof LayoutVisualizeRecordsRoute
}

export interface FileRoutesByTo {
  '/classify': typeof LayoutClassifyRoute
  '/': typeof LayoutIndexRoute
  '/visualize/charts': typeof LayoutVisualizeChartsRoute
  '/visualize/records': typeof LayoutVisualizeRecordsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/classify': typeof LayoutClassifyRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/visualize/charts': typeof LayoutVisualizeChartsRoute
  '/_layout/visualize/records': typeof LayoutVisualizeRecordsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/classify' | '/' | '/visualize/charts' | '/visualize/records'
  fileRoutesByTo: FileRoutesByTo
  to: '/classify' | '/' | '/visualize/charts' | '/visualize/records'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/classify'
    | '/_layout/'
    | '/_layout/visualize/charts'
    | '/_layout/visualize/records'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/classify",
        "/_layout/",
        "/_layout/visualize/charts",
        "/_layout/visualize/records"
      ]
    },
    "/_layout/classify": {
      "filePath": "_layout/classify.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/visualize/charts": {
      "filePath": "_layout/visualize/charts.tsx",
      "parent": "/_layout"
    },
    "/_layout/visualize/records": {
      "filePath": "_layout/visualize/records.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
